# syntax=docker/dockerfile:1
#
ARG IMAGEBASE=frommakefile
#
FROM ${IMAGEBASE}
#
ADD data/rootfs-armv7.tar /
ADD data/qemu-armeb-static /usr/bin/qemu-armeb-static
RUN apk add --no-cache --purge -uU bash \
    && rm -rf /var/cache/apk/* /tmp/*
#
# CMD set on run/test or in child images
ENTRYPOINT ["/bin/bash"]
