ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
ADD data/rootfs.tar /
ADD data/qemu-aarch64-static /usr/bin/qemu-aarch64-static
RUN apk add --no-cache --purge -uU bash && \
    rm -rf /var/cache/apk/* /tmp/*
#
# CMD ["/bin/bash"]
