# syntax=docker/dockerfile:1
#
ARG IMAGEBASE=frommakefile
#
FROM ${IMAGEBASE}
#
ADD data/rootfs-riscv64.tar /
# ADD data/qemu-riscv64-static /usr/bin/qemu-riscv64-static
RUN \
    apk add --no-cache --purge -uU \
        bash \
    && rm -rf /var/cache/apk/* /tmp/*
#
# CMD set on run/test or in child images
ENTRYPOINT ["/bin/bash"]
