# syntax=docker/dockerfile:1
#
ARG IMAGEBASE=frommakefile
#
FROM ${IMAGEBASE}
#
ADD data/rootfs-armhf.tar /
ADD data/qemu-arm-static /usr/bin/qemu-arm-static
RUN apk add --no-cache --purge -uU bash \
    && rm -rf /var/cache/apk/* /tmp/*
#
# CMD set on run/test or in child images
ENTRYPOINT ["/bin/bash"]
